//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTasks.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMember
    {
        public long Id { get; set; }
        public long ProjectId { get; set; }
        public long MemberId { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual User User { get; set; }
    }
}
