//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyTasks.EfDao
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.ProjectMembers = new HashSet<ProjectMember>();
            this.Projects = new HashSet<Project>();
            this.Tasks = new HashSet<Task>();
            this.UsersRelationships = new HashSet<UsersRelationship>();
            this.UsersRelationships1 = new HashSet<UsersRelationship>();
        }
    
        public long Id { get; set; }
        public string Phone { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<ProjectMember> ProjectMembers { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Task> Tasks { get; set; }
        public virtual ICollection<UsersRelationship> UsersRelationships { get; set; }
        public virtual ICollection<UsersRelationship> UsersRelationships1 { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
